### ISSUE TITLE
Peer endpoint port is not packed correctly

### ISSUE THREAD

**Issue by apognu** [mdlayher/wireguardctrl#15]
Hi,

The port of a peer endpoint seems to be transmitted incorrectly to netlink, here are the values set in the ```PeerConfig``` (_left_) struct and the resulting value as reported by ```wg``` (_right_) after calling ```ConfigureDevice```:
 * 10000 -> 4135
 * 51820 -> 27850

**Comment by mdlayher** [comment]
I don't believe this is the actual problem; when spelunking through wg code, I noticed it was making a system call ("getnameinfo"? IIRC) to resolve the endpoint address in some way. I forgot to look into it further, but this issue is a good reminder to do so.

**Comment by mdlayher** [comment]
I'll take a look today, but PRs welcome if you find it first. This sounds like an endianness issue.

**Comment by apognu** [comment]
I think you're reversing the two bytes of the port number.

10000 is 00100111 00010000 in binary.
4135 is 00010000 00100111

So yes, endianness issue probably. I'll look if I can find the issue.

**Comment by mdlayher** [comment]
Should be fixed as of #16.

**Comment by mdlayher** [comment]
Seems to work as expected now:

```go
		cfg := wgtypes.Config{
			ReplacePeers: true,
			Peers: []wgtypes.PeerConfig{{
				PublicKey: priv.PublicKey(),
				Endpoint: &net.UDPAddr{
					IP:   net.IPv4(192, 168, 1, 4),
					Port: 58575,
				},
			}},
		}

		if err := c.ConfigureDevice(d.Name, cfg); err != nil {
			log.Fatalf("failed to configure: %v", err)
		}
```

```
$ sudo ./wgctrl 
interface: wg0
  public key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  private key: (hidden)
  listening port: 0

peer: R65jHoT6fhrk8OFS/L2KiDEP/O/+XrCGfOGzUG3x1j0=
  endpoint: 192.168.1.4:58575
  allowed ips: 
  latest handshake: 1969-12-31 19:00:00 -0500 EST
  transfer: 0 B received, 0 B sent
```

**Comment by apognu** [comment]
Yes, everything's good on my end as well.
