### ISSUE TITLE
wgtypes: Peer bytes types

### ISSUE THREAD

**Issue by bradfitz** [mdlayher/wireguardctrl#8]
https://godoc.org/github.com/mdlayher/wireguardctrl/wgtypes#Peer has

```
    ReceiveBytes                int
    TransmitBytes               int
```

Are those counters of received and transmitted bytes? If so, they should be int64. (Go's default unit for sizes for things that aren't in-memory sizes.)

In any case, docs would be nice.

**Comment by mdlayher** [comment]
SGTM for int64, that's an easy change.

Yeah, docs to come on some of the older types for sure.

**Comment by mdlayher** [comment]
Fixed in https://github.com/mdlayher/wireguardctrl/commit/3fc743e647482f1f60c277c20f520b5339b5088d.

**Comment by mdlayher** [comment]
Updated docs as well: https://godoc.org/github.com/mdlayher/wireguardctrl/wgtypes#Peer.
